---
- name: Instalar Nginx y dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ nginx_packages }}"

- name: Eliminar fichero configuración default
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
    force: "{{ force_nginx }}"

- name: Instalar configuración deseada
  template:
    src: "{{ config_file }}"
    dest: /etc/nginx/sites-available/{{ site_name }}
    owner: root
    group: root
    mode: 0644
    force: "{{ force_nginx }}"

- name: Activar nuevo site
  file:
    src: /etc/nginx/sites-available/{{ site_name }}
    dest: /etc/nginx/sites-enabled/{{ site_name }}
    state: link
    force: "{{ force_nginx }}"
  notify: Reiniciar servicio Nginx
